name: StartupCommands
version: ${project.version}
main: ${main.class}
author: ${author}
description: ${project.description}

commands:
   startup:
      description: Manage the StartupCommands plugin settings.
      usage: /<command> [args]
      permission: startupcommands.manage
      aliases: [startupcommands, startupcommand, startupcmd, sc]
permissions:
   startupcommands.manage:
      description: Allows you to manage the StartupCommands plugin settings
      default: op